name: PHPUnit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php:
          - 8.4
          - 8.5
        dependencies:
          - locked
          - highest

    name: Tests on PHP ${{ matrix.php }} - ${{ matrix.dependencies }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Composer install
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Run tests
        run: composer test
